name: GH Docker Compose with locust load testing
on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up --abort-on-container-exit

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
